name: Your New Jekyll Site
title: Crips Theme for Jekyll
description: "A minimalist, responsive, and open-source theme for Jekyll"
logo: /assets/images/logo.jpg

markdown: kramdown
rouge: true

comments: true
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num"
permalink: /:title.html