# Site settings
title: Limpid Jekyll Theme
email: pranav@maangalabs.com
description: Limpid Jekyll Theme is a clean, minimal theme for Jekyll websites.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://maangalabs.com" # the base hostname & protocol for your site




#permalink /blog/2014/11/11/this-is-a-sample-post
#permalink: /blog/:year/:month/:day/:title/
# Build settings
markdown: kramdown

#Disqus configuration
disqus_short_name: maangalabscom
disqus_show_comment_count: true

#Can be used for multiple author blogs ! Add name to post For more visit the sample
authors:
  pranavrajs:
    display_name: Pranav Raj S
    email: pranavrajs@gmail.com
   