name: Your New Jekyll Site
title: äìÏæÒ¹Óê
#description: "A minimalist, responsive, and open-source theme for Jekyll"
logo: /assets/images/logo.jpg

markdown: kramdown
pygments: true


paginate: 5
paginate_path: "/page:num"
permalink: /:title.html