# Site settings
title: Jekyll's Ramblings
description: "This is my tech blog containing random thoughts and code snippets"
baseurl: "symi.top"
url: "http://yourdomain.com"
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
permalink: pretty
